### ISSUE TITLE
Datapack Customization

### ISSUE THREAD

**Issue by Rystyles** [Andrew6rant/Tiered#5]
Admittedly I am decently new to datapack creation, especially with fabric versions of minecraft. I have been trying to make my own datapack for this mod so I can edit and create custom modifiers for tools and armor. I was wondering if there may be a quick step-by-step guide available for creating such things for this mod, or even if a placeholder datapack for this mod is available for download and editing somewhere?

Any help is appreciated, thank you!

**Comment by Andrew6rant** [comment]
Which version of this mod are you trying to make a datapack for? The datapack formats for the 1.16 version and Forge port are different than the format that is on this repo.

Currently, my fork of this mod is in a bit of a state of limbo, I've put development on hold since schoolwork was ramping up and it only runs on 1.18-pre5. The semester has since ended and now I am a bit more free this summer to work on it. Soon, I will update this mod for 1.18.2 and 1.19, and I'll publish an example datapack when it releases.

The data format for the original 1.16 mod is detailed here: https://github.com/Draylar/tiered#customization This is also the same format that the Forge version uses.

**Comment by Rystyles** [comment]
I am trying to make a datapack for the Fabric 1.0.3.jar version of the mod. 

A few friends and I are trying to setup a Vanilla+ Minecraft server and this mod looked great, and after searching around the original authors version of the mod I ended up here, glad to see progress is still being made on this awesome mod! 

An example datapack would be awesome whenever you are able to get around to it, I completely understand school and other such priorities, there's no rush! 😄

**Comment by Andrew6rant** [comment]
Oh wow, 1.0.3! That is a pretty old version, for 1.15.2, well before I started development on my fork. I won't support that version if you find any bugs, but I whipped up a quick example datapack (and resource pack) for you. It adds three new modifiers:

- nimble (for axe and sword, increases attack speed by 10% and attack reach by 1)
- armored (for armor, adds +1 to armor value)
- brisk (for armor, increases movement speed by 10%)

I think the datapack is pretty self-explanatory, all you need to do is create a `mod_id` name (I picked `tieredexample`) and place your .json files inside of the `item_attributes` folder. They can be in any sub-folder inside of that, I just separated armor and held items for easier organization.

In the json, the name and id field have to match each other and the beginning part needs to be your `mod_id`. The tags are whatever you want the tier to apply to. Style is any of Minecraft's color codes in all caps, etc. (see Draylar's README for more detail)

The resource pack just adds names for the new tiers. Instead of seeing `tieredexample:nimble.label`, you'd see `Nimble`. You can apply it with a server-resource pack if you know how to do that.

Here are the files:
[tiered example datapack.zip](https://github.com/Andrew6rant/tiered/files/8750871/tiered.example.datapack.zip)
[tiered example resourcepack.zip](https://github.com/Andrew6rant/tiered/files/8750873/tiered.example.resourcepack.zip)

**Comment by Rystyles** [comment]
Well, what do you know, 1.0.3 is old! I just went back and checked the curseforge website to see what version(s) were available, I had no idea I was running it on such an old version. That's completely my mistake. 

For clarification, I should mention I am trying to setup a 1.18.2 Fabric server, seemingly enough the 1.0.3.jar works decently fine, as in allowing tools to be crafted and then that they are given a modifier. 

I do really appreciate you making the datapack + resource pack for me though! Unfortunately because of my miscommunication I'm afraid they still do not work, I apologize for that again. I will go back and download the latest .jar file available, (I believe that is the 1.2.2.jar?), and try to work around with that version of the mod.

EDIT: So after installing the latest jar, the game does not seem to launch and is resulted in a crash error, interesting that an older jar for the mod works just fine for an updated version of the game haha!

**Comment by Andrew6rant** [comment]
There currently is no version of Tiered that is built for 1.18.2. That's what I mentioned earlier, my current code is a bit of a mangled mess that I've paused due to schoolwork. It is still WIP, but I've added a bunch to this mod, as you can see through the [contribution chart](https://github.com/Andrew6rant/tiered/graphs/contributors):

- Reforging Station and Tier rerolling
- Weighted tiers for more and less rare modifiers
- Size modifier
- Step height modifier
- Support for fishing rod and shield tags
- Tooltip customization (custom image, border color, tier rendering, animated tooltip)
- 20+ new default item_attributes
- etc.

The [wiki](https://github.com/Andrew6rant/tiered/wiki) is a bit dated (last updated in Oct 2021), but it details more of my plans for this mod.

Here is a small showcase of features I added in September 2021, lol:
<details>
<summary>Open Spoiler</summary>

https://user-images.githubusercontent.com/57331134/169748060-0317bb05-007a-42dd-bd69-0232a21a4ba2.mp4

https://user-images.githubusercontent.com/57331134/169748071-2e0f5241-9515-4b0c-a955-c6593f51a857.mp4

</details>

It is just so crazy that version 1.0.3 works on 1.18.2. I started working on this mod at version 1.2.2 which did not work with 1.17 (1.18 hadn't released yet), so I never even thought to test older versions for compatibility. I guess that the serialization and server sync fixes since 1.0.3 must've made the newer versions incompatible.

A proper 1.18.2 version will come in time, but if you want for now, you can use version 1.0.3 on 1.18.2. No warranty provided though, haha. And no guarantee of data retention updating 1.0.3 to what will probably release as 2.1.0.

**Comment by Rystyles** [comment]
I apologize for the hassle then, though your help and work is very appreciated! Cant wait to see what the future holds for this mod.

I will wait patiently for when the 1.18.2 version is released, until then take care, and once again thank you for the help!

**Comment by Andrew6rant** [comment]
Hey @Rystyles, this isn't a release, but I finally have a early beta of Tiered for 1.18.2 (thanks to the code by enjarai and Nilinking).

You can download the .jar off of the artifacts of the latest Actions' run: https://github.com/Andrew6rant/tiered/actions. (Make sure **_not_** to use the -dev, -sources, or -sources-dev .jars)

There is no crafting recipe for the Reforging station, but everything else should work as intended. Note that this is in active development and I won't guarantee compatibility with future updates of the mod.

I haven't tested out any datapacks, but they should work. The example one I gave for 1.15.2 is of a different format than 1.18.2 and won't work. The README of this repo has the updated syntax. (also the tiers in the datapack I gave are already implemented in the 1.18.2 version)

EDIT: Actually, if you could just use build 78: "properly drain xp on reforge," that would be the best. I am going to make commits in the future that will not be stable
